POST  http://localhost:4000/api/login 
Content-Type: application/json

{
    "username":"kusaljr",
    "password":"nigger"
}

###

GET http://localhost:4000/api/login
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJfaWQiOjEsInVzZXJuYW1lIjoia3VzYWxqciJ9LCJpYXQiOjE2MjI5NTc4OTcsImV4cCI6MTYyMjk2NTA5N30.LdCke_dVVzo_5Gx5McK-2p29KuF6TbjfvnrpQpTE9FU
