const mongoose = require("mongoose");

const reqString = {
  type: String,
  required: true,
  trim: true,
};

const reqNum = {
  type: Number,
  required: true,
  default: 0,
};

const playerSchema = mongoose.Schema({
  // id is autogenerated no need to create any paxi name arko rakhna milxa.
  role: { ...reqString, enum: ["CD", "GK", "FW", "CD"] },
  playerName: reqString,
  teamId: { type: mongoose.Schema.Types.ObjectId, ref: "Team" }, //foreign
  goals: reqNum,
  assists: reqNum,
  cleanSheets: {
    type: Boolean,
    default: false,
  },
  points: reqNum,
});

module.exports = mongoose.model("Player", playerSchema);
